# nixpath and opam are set at the same time, so we just check for nix but really we should check for both,
if [ -z $NIX_PATH ]; then
	echo 'NIX_PATH not set, setting NIX_PATH'
	eval `opam config env`
	source /Users/gregory.nisbet/.nix-profile/etc/profile.d/nix.sh
fi
